// Generated by IcedCoffeeScript 1.3.1b
var Overlay,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Overlay = (function() {

  Overlay.name = 'Overlay';

  function Overlay(options) {
    this.request = __bind(this.request, this);
    this.type = options.type != null ? options.type : "SDSS";
    this.view = options.view != null ? options.view : null;
    if (this.type === "SDSS") {
      this.requestImage = this.requestSDSS;
    } else {
      this.requestImage = this.requestFIRST;
    }
    this.view.attach(this);
  }

  Overlay.prototype.notify = function(type, info) {
    switch (type) {
      case "display":
        return display(info);
      case "request":
        return request(info);
      default:
        break;
    }
  };

  Overlay.prototype.request = function(req) {
    var x, y, _ref;
    _ref = [req.x * .512, req.y * .512], x = _ref[0], y = _ref[1];
    return this.requestImage(x, y);
  };

  Overlay.prototype.requestSDSS = function(degX, degY) {};

  return Overlay;

})();
