// Generated by IcedCoffeeScript 1.3.1b
var ImageProxy, Overlay,
  __slice = [].slice,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

window.iced = {
  Deferrals: (function() {

    function _Class(_arg) {
      this.continuation = _arg;
      this.count = 1;
      this.ret = null;
    }

    _Class.prototype._fulfill = function() {
      if (!--this.count) return this.continuation(this.ret);
    };

    _Class.prototype.defer = function(defer_params) {
      var _this = this;
      ++this.count;
      return function() {
        var inner_params, _ref;
        inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (defer_params != null) {
          if ((_ref = defer_params.assign_fn) != null) {
            _ref.apply(null, inner_params);
          }
        }
        return _this._fulfill();
      };
    };

    return _Class;

  })(),
  findDeferral: function() {
    return null;
  }
};
window.__iced_k = window.__iced_k_noop = function() {};

ImageProxy = (function() {

  ImageProxy.name = 'ImageProxy';

  function ImageProxy(imgURL, placeholder) {
    var _this = this;
    this.currentImage = placeholder;
    this.realImage = new Image();
    this.realImage.onload = function() {
      return _this.currentImage = _this.realImage;
    };
    this.realImage.src = imgURL;
  }

  ImageProxy.prototype.display = function() {
    return this.currentImage;
  };

  return ImageProxy;

})();

Overlay = (function() {

  Overlay.name = 'Overlay';

  function Overlay(options) {
    this.setPlaceholder = __bind(this.setPlaceholder, this);

    this.setAlpha = __bind(this.setAlpha, this);

    this.display = __bind(this.display, this);

    this.request = __bind(this.request, this);
    this.buffer = {};
    this.placeholder = options.placeholder;
    this.type = options.type != null ? options.type : "SDSS";
    this.view = options.view != null ? options.view : null;
    this.alpha = options.alpha != null ? options.alpha : 1.0;
    this.imagePath = '';
    if (this.type === "SDSS") {
      this.requestImage = this.requestSDSS;
    } else if (this.type === "FIRST") {
      this.requestImage = this.requestFIRST;
      this.imagePath = options.imagepath != null ? options.imagepath : '../../images/';
    }
    if (this.view) this.view.attach(this);
  }

  Overlay.prototype.update = function(type, info) {
    switch (type) {
      case "display":
        return this.display(info);
      case "request":
        return this.request(info);
      case "static":
        break;
      default:
        break;
    }
  };

  Overlay.prototype.request = function(req) {
    var imgProxy, x, y, ___iced_passed_deferral, __iced_deferrals, __iced_k, _ref,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    _ref = [req.x * .512, req.y * .512], x = _ref[0], y = _ref[1];
    if ((this.buffer[req.x] != null) && (this.buffer[req.x][req.y] != null)) {
      return;
      return __iced_k();
    } else {
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/home/sean/site/Astro/tests/Overlay.iced",
          funcname: "Overlay.request"
        });
        _this.requestImage(x, y, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return imgProxy = arguments[0];
            };
          })(),
          lineno: 41
        }));
        __iced_deferrals._fulfill();
      })(function() {
        return __iced_k((_this.buffer[req.x] != null) ? _this.buffer[req.x][req.y] = imgProxy : (_this.buffer[req.x] = {}, _this.buffer[req.x][req.y] = imgProxy));
      });
    }
  };

  Overlay.prototype.display = function(info) {
    if (this.buffer[info.x] && this.buffer[info.x][info.y]) {
      info.ctx.save();
      info.ctx.globalAlpha = this.alpha;
      info.ctx.translate(-info.x * 1024, info.y * 1024);
      if (this.buffer[info.x][info.y].display()) {
        info.ctx.drawImage(this.buffer[info.x][info.y].display(), 0, 0);
      }
      return info.ctx.restore();
    }
  };

  Overlay.prototype.requestSDSS = function(degX, degY, cb) {
    var decMax, decMin, imgProxy, newurl, raMax, raMin;
    decMin = degY - .256;
    decMax = degY + .256;
    raMax = degX + .256;
    raMin = degX - .256;
    newurl = "http://astro.cs.pitt.edu/astroshelfTIM/db/remote/SDSS.php?scale=" + 1.8 + "&ra=" + degX + "&dec=" + degY + "&width=1024&height=1024";
    imgProxy = new ImageProxy(newurl, this.placeholder);
    cb(imgProxy);
    return this.view.display();
  };

  Overlay.prototype.requestFIRST = function(degX, degY, cb) {
    var data, decMax, decMin, imgProxy, raMax, raMin, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    decMin = degY - .256;
    decMax = degY + .256;
    raMax = degX + .256;
    raMin = degX - .256;
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "/home/sean/site/Astro/tests/Overlay.iced",
        funcname: "Overlay.requestFIRST"
      });
      $.get('http://astro.cs.pitt.edu/astroshelfTIM/db/remote/SPATIALTREE.php', {
        RAMin: raMin,
        RAMax: raMax,
        DecMin: decMin,
        DecMax: decMax
      }, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return data = arguments[0];
          };
        })(),
        lineno: 70
      }), 'json');
      __iced_deferrals._fulfill();
    })(function() {
      if (data[0]) {
        imgProxy = new ImageProxy(_this.imagepath + data[0], _this.placeholder);
      } else {
        imgProxy = new ImageProxy(_this.placeholder, _this.placeholder);
      }
      cb(imgProxy);
      return _this.view.display();
    });
  };

  Overlay.prototype.setAlpha = function(newAlpha) {
    return this.alpha = newAlpha;
  };

  Overlay.prototype.setPlaceholder = function(newPlaceholder) {
    return this.placeholder = newPlaceholder;
  };

  return Overlay;

})();
