// Generated by IcedCoffeeScript 1.3.1b
var __slice = [].slice;

window.iced = {
  Deferrals: (function() {

    function _Class(_arg) {
      this.continuation = _arg;
      this.count = 1;
      this.ret = null;
    }

    _Class.prototype._fulfill = function() {
      if (!--this.count) return this.continuation(this.ret);
    };

    _Class.prototype.defer = function(defer_params) {
      var _this = this;
      ++this.count;
      return function() {
        var inner_params, _ref;
        inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (defer_params != null) {
          if ((_ref = defer_params.assign_fn) != null) {
            _ref.apply(null, inner_params);
          }
        }
        return _this._fulfill();
      };
    };

    return _Class;

  })(),
  findDeferral: function() {
    return null;
  }
};
window.__iced_k = window.__iced_k_noop = function() {};

$(document).ready(function() {
  var click, di, overlayFIRST, placeholder, view, ___iced_passed_deferral, __iced_deferrals, __iced_k,
    _this = this;
  __iced_k = __iced_k_noop;
  ___iced_passed_deferral = iced.findDeferral(arguments);
  placeholder = new Image();
  (function(__iced_k) {
    __iced_deferrals = new iced.Deferrals(__iced_k, {
      parent: ___iced_passed_deferral,
      filename: "/home/sean/site/Astro/tests/Startup.coffee"
    });
    placeholder.onload = __iced_deferrals.defer({
      lineno: 3
    });
    placeholder.src = "placeholder.jpg";
    __iced_deferrals._fulfill();
  })(function() {
    di = document.getElementById("container");
    view = new View(di);
    overlayFIRST = new Overlay({
      type: "FIRST",
      alpha: .8,
      "view": view,
      placeholder: placeholder
    });
    click = function() {
      view.display();
      return setTimeout(click, 15);
    };
    return click();
  });
});
