// Generated by IcedCoffeeScript 1.3.1b
(function() {
  var Overlay, iced, overlay, __iced_k, __iced_k_noop,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  Overlay = (function() {

    Overlay.name = 'Overlay';

    function Overlay(options) {
      this.request = __bind(this.request, this);
      this.type = options.type != null ? options.type : "SDSS";
      this.view = options.view != null ? options.view : null;
      if (this.type === "SDSS") {
        this.requestImage = this.requestSDSS;
      } else {
        this.requestImage = this.requestFIRST;
      }
      if (this.view) this.view.attach(this);
    }

    Overlay.prototype.notify = function(type, info) {
      switch (type) {
        case "display":
          return display(info);
        case "request":
          return request(info);
        default:
          break;
      }
    };

    Overlay.prototype.request = function(req) {
      var x, y, _ref;
      _ref = [req.x * .512, req.y * .512], x = _ref[0], y = _ref[1];
      return this.requestImage(x, y);
    };

    Overlay.prototype.requestSDSS = function(degX, degY) {};

    Overlay.prototype.requestFIRST = function(degX, degY) {
      var data, decMax, decMin, raMax, raMin, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      decMin = degY - .256;
      decMax = degY + .256;
      raMax = degX - .256;
      raMin = degX + .256;
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/Overlay.iced",
          funcname: "Overlay.requestFIRST"
        });
        $.post("request.php", __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return data = arguments[0];
            };
          })(),
          lineno: 28
        }), 'text');
        __iced_deferrals._fulfill();
      })(function() {
        return alert(data);
      });
    };

    return Overlay;

  })();

  overlay = new Overlay({
    type: "FIRST"
  });

  overlay.requestFIRST(0, 0);

}).call(this);
