// Generated by CoffeeScript 1.3.2
var SkyView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SkyView = (function(_super) {

  __extends(SkyView, _super);

  SkyView.HTM = 0;

  SkyView.rotation = null;

  SkyView.translation = null;

  SkyView.renderMode = 0;

  function SkyView(options) {
    this.keyPressed = __bind(this.keyPressed, this);

    this.render = __bind(this.render, this);
    SkyView.__super__.constructor.call(this, options);
    this.HTM = new HTM(3, this.gl);
    this.rotation = [20.0, 0.0, 0.0];
    this.translation = [0.0, 0.0, 0.0];
    this.renderMode = this.gl.TRIANGLES;
    this.render();
  }

  SkyView.prototype.render = function() {
    this.preRender();
    this.HTM.bind(this.gl, this.shaderProgram);
    this.postRender(this.rotation, this.translation);
    this.HTM.render(this.gl, this.renderMode);
  };

  SkyView.prototype.keyPressed = function(key) {
    switch (String.fromCharCode(key.which)) {
      case 'i':
        this.rotation[0]++;
        break;
      case 'k':
        this.rotation[0]--;
        break;
      case 'l':
        this.rotation[1]++;
        break;
      case 'j':
        this.rotation[1]--;
        break;
      case 'w':
        this.translation[2] += 0.1;
        break;
      case 's':
        this.translation[2] -= 0.1;
        break;
      case '0':
        this.HTM = new HTM(0, this.gl);
        break;
      case '1':
        this.HTM = new HTM(1, this.gl);
        break;
      case '2':
        this.HTM = new HTM(2, this.gl);
        break;
      case '3':
        this.HTM = new HTM(3, this.gl);
        break;
      case '4':
        this.HTM = new HTM(4, this.gl);
        break;
      case '5':
        this.HTM = new HTM(5, this.gl);
        break;
      case '6':
        this.HTM = new HTM(6, this.gl);
        break;
      case '7':
        this.HTM = new HTM(7, this.gl);
        break;
      case '8':
        this.HTM = new HTM(8, this.gl);
    }
    this.render();
  };

  return SkyView;

})(WebGL);
