// Generated by CoffeeScript 1.3.2
var SkyView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

SkyView = (function(_super) {

  __extends(SkyView, _super);

  SkyView.HTM = 0;

  function SkyView(options) {
    this.render = __bind(this.render, this);
    SkyView.__super__.constructor.call(this, options);
    this.HTM = new HTM(3, this.gl);
    this.render();
  }

  SkyView.prototype.render = function() {
    this.preRender();
    this.HTM.bind(this.gl, this.shaderProgram);
    this.postRender();
    return this.HTM.render(this.gl);
  };

  return SkyView;

})(WebGL);
